# .github/workflows/deploy-backend.yml
name: Deploy Backend

on:
  push:
    branches:
      - uat
    paths:
      - 'backend/**'

concurrency:
  group: deploy-backend-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure SSH
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -t rsa,ed25519,ecdsa ${{ secrets.BACKEND_EC2_HOST }} >> ~/.ssh/known_hosts

        cat << 'EOF' > ~/.ssh/id_rsa_back
        ${{ secrets.BACKEND_EC2_SSH_KEY }}
        EOF
        chmod 600 ~/.ssh/id_rsa_back

    - name: Sync backend to EC2
      env:
        RSYNC_RSH: "ssh -i ~/.ssh/id_rsa_back -o StrictHostKeyChecking=yes"
      run: |
        rsync -avz --delete \
          backend/ ${{ secrets.BACKEND_EC2_USER }}@${{ secrets.BACKEND_EC2_HOST }}:/home/${{ secrets.BACKEND_EC2_USER }}/Llumi/backend/

    - name: Install dependencies on EC2
      run: |
        ssh -T -o BatchMode=yes \
          -i ~/.ssh/id_rsa_back \
          -o StrictHostKeyChecking=yes \
          ${{ secrets.BACKEND_EC2_USER }}@${{ secrets.BACKEND_EC2_HOST }} 'cd ~/Llumi/backend && npm install --production'
    # - name: Install & Restart with PM2
    #   run: |
    #     ssh -T -o BatchMode=yes \
    #         -i ~/.ssh/id_rsa_back \
    #         -o StrictHostKeyChecking=yes \
    #         ${{ secrets.BACKEND_EC2_USER }}@${{ secrets.BACKEND_EC2_HOST }} << 'EOF'
    #         set -e
    #         cd ~/Llumi/backend
    #         npm install
    #         pm2 reload ecosystem.config.js --env uat
    #         pm2 save
    #         EOF
